server:
  port: 8761

spring:
  application:
    name: discoveryservice
    
eureka:
  client:
    register-with-eureka: false   # euraka의 registry에 등록할지 여부를 설정, 자신이 서버기 때문에 등록이 불필요
    fetch-registry: false         # registy에 있는 정보를 가져올지 여부를 설정, 자신이 서버기 때문에 등록이 불필요
    serviceUrl:
      defaultZone: https://eureka-dygys.run.goorm.site/     # 물리적으로 다른곳 위치의 eureka에도 등록 관리 가능      
  server:
    wait-time-in-ms-when-sync-empty: 5      # 서버가 요청을 받기 전 대기할 초기 시간(ms) : 거의 대기 없음 (default 5분 : 상용에서는 모든 서비스가 등록 되길 기다리기 위해 5분 후 정보를 공유)
    response-cache-update-interval-ms: 3000 # 서비스에게 제공을 위해Eureka는 서비스들의 정보를 캐싱하며, 캐싱을 업데이트하는 주기를 설정한다.          
