server:
  port: 0

spring:
  application:
    name: user-service
  h2:                                 #개발 편의성을 위해 로컬 H2 DB사용
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    registry:
      default-open-for-traffic-count: 0		#다중의 Eureka 에 등록
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://davinchiview.run.goorm.site/,http://localhost:8761/eureka/

# 환영 메시지를 위한 greeting
greeting:
  message: Welcome to Davinchiview World Fight!!!!
