server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/davinchiview?serverTimezone=UTC&characterEncoding=UTF-8
    username: davinchiview
    password: ekqbWkd1004!
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: "optional:configserver:http://localhost:8888/"

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka/   # 설정을 하지 않으면 기본 http://localhost:8761/ 로 연동된다.

# 환영 메시지를 위한 greeting
greeting:
  message: github Config setting infomation!!!!!!!!!!!!!
